verbose: True
manual_episode_accept: False
scenario_files: ["overtaking.yaml"]

ho_bearing_range: [-3.0, 3.0] # [-20.0, 20.0], [-15.0, 15.0], [-10.0, 10.0], [-5.0, 5.0]
ho_course_range: [-5.0, 5.0]
ot_bearing_range: [-12.5, 12.5] # [-20.0, 20.0]
ot_course_range: [-8.0, 8.0] # [-15.0, 15.0]
cr_bearing_range: [10.1, 90.5]
cr_course_range: [-10.0, 10.0]
dist_between_ships_range: [400, 4000.0] #[500.0, 800.0], [300.0, 800.0], [500.0, 800.0]
gaussian_csog_state_perturbation_covariance: [1000.0, 1000.0, 2.0, 10.0] # for state [x, y, U, chi], with last entry in degrees
perpendicular_csog_state_perturbation_pm_range: [2500.0, 2.0, 10.0] # +- uniform ranges in [distance, speed, course (in deg)]
t_cpa_threshold: 800.0
d_cpa_threshold: 800.0

behavior_generator:
  ownship_method: "VaryingSpeedConstantCourse" # Either "ConstantSpeedAndCourse", "VaryingSpeedConstantCourse", "ConstantSpeedRandomWaypoints", "VaryingSpeedRandomWaypoints", "RRT", "RRTStar", "PQRRTStar", "Randomize"
  target_ship_method: "ConstantSpeedRandomWaypoints" # Either "ConstantSpeedAndCourse", "ConstantSpeedRandomWaypoints", "VaryingSpeedRandomWaypoints", "RRT", "RRTStar", "PQRRTStar", "Randomize" 
  target_ship_rrt_behavior_sampling_method: "OwnshipWaypointCorridor" # Either "Optimal", "UniformlyInMap", "CourseCorridor", "CPA", "OwnshipGoal", "OwnshipWaypointCorridor", "Randomized"

  n_wps_range: [6, 11]
  speed_plan_variation_range: [-1.0, 1.0]
  waypoint_dist_range: [250.0, 400.0]
  waypoint_ang_range: [-17.5, 17.5]
  hazard_buffer: 10.0

  # Can use 3 different RRT-algorithms for behavior generation: PQ-RRT*, Informed RRT* and RRT:
  pqrrtstar:
    params:
      max_nodes: 3000
      max_iter: 25000
      max_time: 2.0
      iter_between_direct_goal_growth: 100
      min_node_dist: 5.0
      goal_radius: 200.0
      step_size: 2.5
      min_steering_time: 1.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
      gamma: 2000.0
      max_sample_adjustments: 0
      lambda_sample_adjustment: 4.0
      safe_distance: 40.0
      max_ancestry_level: 1
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 1000.0
      cross_track_error_int_threshold: 30.0
  
  rrtstar:
    params:
      max_nodes: 3000
      max_iter: 10000
      max_time: 2.0
      iter_between_direct_goal_growth: 100
      min_node_dist: 5.0
      goal_radius: 200.0
      step_size: 2.5
      min_steering_time: 1.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
      gamma: 2000.0
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 1000.0
      cross_track_error_int_threshold: 30.0

  rrt:
    params:
      max_nodes: 3000
      max_iter: 25000
      max_time: 2.0
      iter_between_direct_goal_growth: 100
      goal_radius: 200.0
      step_size: 2.5
      min_steering_time: 2.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 1000.0
      cross_track_error_int_threshold: 30.0
